# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pve_win10_1\Desktop\gnss-downloader\code\gui_high_dpi.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(671, 717)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lib/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("lib/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.checkBox_rnx_o = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rnx_o.setGeometry(QtCore.QRect(160, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_rnx_o.setFont(font)
        self.checkBox_rnx_o.setObjectName("checkBox_rnx_o")
        self.checkBox_rnx_n = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rnx_n.setGeometry(QtCore.QRect(320, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_rnx_n.setFont(font)
        self.checkBox_rnx_n.setObjectName("checkBox_rnx_n")
        self.checkBox_rnx_m = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rnx_m.setGeometry(QtCore.QRect(490, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_rnx_m.setFont(font)
        self.checkBox_rnx_m.setObjectName("checkBox_rnx_m")
        self.checkBox_o = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_o.setGeometry(QtCore.QRect(160, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_o.setFont(font)
        self.checkBox_o.setObjectName("checkBox_o")
        self.checkBox_n = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_n.setGeometry(QtCore.QRect(320, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_n.setFont(font)
        self.checkBox_n.setObjectName("checkBox_n")
        self.checkBox_m = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_m.setGeometry(QtCore.QRect(490, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_m.setFont(font)
        self.checkBox_m.setObjectName("checkBox_m")
        self.checkBox_igs_sp3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_igs_sp3.setGeometry(QtCore.QRect(160, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_igs_sp3.setFont(font)
        self.checkBox_igs_sp3.setObjectName("checkBox_igs_sp3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.dateEdit_start = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_start.setGeometry(QtCore.QRect(200, 160, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_start.setFont(font)
        self.dateEdit_start.setObjectName("dateEdit_start")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 150, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.dateEdit_end = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_end.setGeometry(QtCore.QRect(450, 160, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_end.setFont(font)
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 150, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 230, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.textEdit_stations = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_stations.setGeometry(QtCore.QRect(340, 220, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_stations.setFont(font)
        self.textEdit_stations.setObjectName("textEdit_stations")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 320, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.radioButton_wuhan = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_wuhan.setGeometry(QtCore.QRect(150, 330, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_wuhan.setFont(font)
        self.radioButton_wuhan.setChecked(True)
        self.radioButton_wuhan.setObjectName("radioButton_wuhan")
        self.radioButton_nasa = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_nasa.setGeometry(QtCore.QRect(430, 330, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_nasa.setFont(font)
        self.radioButton_nasa.setObjectName("radioButton_nasa")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(150, 370, 791, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.pushButton_path = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_path.setGeometry(QtCore.QRect(510, 440, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_path.setFont(font)
        self.pushButton_path.setObjectName("pushButton_path")
        self.pushButton_download = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_download.setGeometry(QtCore.QRect(40, 500, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_download.setFont(font)
        self.pushButton_download.setObjectName("pushButton_download")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(490, 500, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_about.setFont(font)
        self.pushButton_about.setObjectName("pushButton_about")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 630, 551, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(40, 570, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_info.setFont(font)
        self.label_info.setTextFormat(QtCore.Qt.AutoText)
        self.label_info.setObjectName("label_info")
        self.label_path = QtWidgets.QLabel(self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(140, 440, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_path.setFont(font)
        self.label_path.setTextFormat(QtCore.Qt.AutoText)
        self.label_path.setObjectName("label_path")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(150, 410, 791, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName("label_10")
        self.checkBox_igu_sp3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_igu_sp3.setGeometry(QtCore.QRect(320, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_igu_sp3.setFont(font)
        self.checkBox_igu_sp3.setObjectName("checkBox_igu_sp3")
        self.checkBox_igr_sp3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_igr_sp3.setGeometry(QtCore.QRect(490, 110, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_igr_sp3.setFont(font)
        self.checkBox_igr_sp3.setObjectName("checkBox_igr_sp3")
        self.pushButton_open_save_path = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_save_path.setGeometry(QtCore.QRect(270, 500, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_open_save_path.setFont(font)
        self.pushButton_open_save_path.setObjectName("pushButton_open_save_path")
        self.pushButton_english = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_english.setGeometry(QtCore.QRect(380, 500, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_english.setFont(font)
        self.pushButton_english.setObjectName("pushButton_english")
        self.pushButton_shoudong = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shoudong.setGeometry(QtCore.QRect(150, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_shoudong.setFont(font)
        self.pushButton_shoudong.setObjectName("pushButton_shoudong")
        self.pushButton_auto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_auto.setGeometry(QtCore.QRect(150, 260, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_auto.setFont(font)
        self.pushButton_auto.setObjectName("pushButton_auto")
        self.pushButton_pause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pause.setGeometry(QtCore.QRect(160, 500, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setObjectName("pushButton_pause")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GNSS数据下载器     V3.1   By mereith."))
        self.label.setText(_translate("MainWindow", "请选择文件类型"))
        self.checkBox_rnx_o.setText(_translate("MainWindow", "rnx3.x观测文件"))
        self.checkBox_rnx_n.setText(_translate("MainWindow", "rnx3.x广播星历"))
        self.checkBox_rnx_m.setText(_translate("MainWindow", "rnx3.x气候文件"))
        self.checkBox_o.setText(_translate("MainWindow", "rnx2.x观测文件"))
        self.checkBox_n.setText(_translate("MainWindow", "rnx2.x广播星历"))
        self.checkBox_m.setText(_translate("MainWindow", "rnx2.x气候文件"))
        self.checkBox_igs_sp3.setText(_translate("MainWindow", "igs事后精密星历"))
        self.label_2.setText(_translate("MainWindow", "请选择起始时间"))
        self.label_3.setText(_translate("MainWindow", "起始："))
        self.label_4.setText(_translate("MainWindow", "结束："))
        self.label_5.setText(_translate("MainWindow", "请选择特定观测站"))
        self.textEdit_stations.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">请点击模式选择按钮.否则默认所有观测站.</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "请选择下载源"))
        self.radioButton_wuhan.setText(_translate("MainWindow", "武汉(igs.gnsswhu.cn)"))
        self.radioButton_nasa.setText(_translate("MainWindow", "NASA(cddis.nasa.gov)"))
        self.label_7.setText(_translate("MainWindow", "NASA的数据全，但是国内直连下载慢"))
        self.label_8.setText(_translate("MainWindow", "请选择保存目录"))
        self.pushButton_path.setText(_translate("MainWindow", "选择目录"))
        self.pushButton_download.setText(_translate("MainWindow", "开始下载"))
        self.pushButton_about.setText(_translate("MainWindow", "关于"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.label_info.setText(_translate("MainWindow", "请做好选择并点击开始下载           (目前只支持gps数据下载.有人用我就更新一下.)"))
        self.label_path.setText(_translate("MainWindow", "   请选择保存目录"))
        self.label_10.setText(_translate("MainWindow", "武汉的下载快，但数据不那么全"))
        self.checkBox_igu_sp3.setText(_translate("MainWindow", "igu快速精密星历"))
        self.checkBox_igr_sp3.setText(_translate("MainWindow", "igr预报精密星历"))
        self.pushButton_open_save_path.setText(_translate("MainWindow", "打开下载目录"))
        self.pushButton_english.setText(_translate("MainWindow", "English"))
        self.pushButton_shoudong.setText(_translate("MainWindow", "手动指定"))
        self.pushButton_auto.setText(_translate("MainWindow", "根据卫星号自动选择"))
        self.pushButton_pause.setText(_translate("MainWindow", "暂停"))
